# Project Information
site_name: Flairminds blog
site_url: https://blogs.flairminds.com
site_description: >-
  Engineering blogs and guides from Flairminds Software Pvt. Ltd.

# Repository
repo_name: Flairminds/blogs
repo_url: https://github.com/Flairminds/blogs

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.section
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - search
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow

nav:
  - Blog:
      - blog/index.md

plugins:
  - blog:
      blog_dir: blog
  - minify:
      minify_html: true

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  Social:
    - icons: fontawesome/brands/github
      link: https://github.com/Flairminds

markdown_extensions: 
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: Flairminds
      repo: blogs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde