authors:
  atharvab:
    name: Atharva Bhandvalkar
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/70326109
    url: https://github.com/a-tharva
  amanw:
    name: Aman Walekar
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/91743769
    url: https://github.com/AmanWalekar